### ISSUE TITLE
LEMS/NML2 example 3 does not work with neuron

### ISSUE THREAD

**Issue by borismarin** [NeuroML/NeuroML2#65]
`jnml LEMS_NML2_Ex3_Net.xml -neuron` fails:

```
 jNeuroML v0.7.3
(INFO) Reading from: /Users/borismarin/git/NeuroML2/LEMSexamples/LEMS_NML2_Ex3_Net.xml
(INFO) Adding simulation Component(id=sim1 type=Simulation) of network/component: net1 (Type: network)
(INFO) -- Writing to mod: /Users/borismarin/git/NeuroML2/LEMSexamples/hhcell_1.mod
(INFO) -- Writing to mod: /Users/borismarin/git/NeuroML2/LEMSexamples/hhcell_2.mod
(INFO) -- Writing to mod: /Users/borismarin/git/NeuroML2/LEMSexamples/syn2exp.mod
(INFO) -- Writing to mod: /Users/borismarin/git/NeuroML2/LEMSexamples/syn1exp.mod
(INFO) -- Writing to mod: /Users/borismarin/git/NeuroML2/LEMSexamples/pulseGen1.mod
Exception in thread "main" java.lang.NullPointerException
    at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getExposure(LEMSQuantityPathNeuron.java:61)
    at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getExposure(LEMSQuantityPathNeuron.java:74)
    at org.neuroml.export.neuron.LEMSQuantityPathNeuron.getDimension(LEMSQuantityPathNeuron.java:83)
    at org.neuroml.export.neuron.NeuronWriter.getMainScript(NeuronWriter.java:1150)
    at org.neuroml.export.neuron.NeuronWriter.generateMainScriptAndMods(NeuronWriter.java:186)
    at org.neuroml.export.neuron.NeuronWriter.generateAndRun(NeuronWriter.java:115)
    at org.neuroml.JNeuroML.main(JNeuroML.java:396)
```

**Comment by pgleeson** [comment]
Fixed in development branch
